name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Ensure build/chapters directory exists
        run: mkdir -p build/chapters
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            figures/convergence.tex
            figures/lattice.tex
            main.tex
          args: -lualatex -file-line-error -halt-on-error -interaction=nonstopmode -outdir=build
          latexmk_use_lualatex: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: build/main.pdf
